services:
  server:
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - db_mysql

  db_mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

